//
// Created by tarabasz on 11/27/23.
//

#ifndef SEMANTIC_REACH_TEST_RIGHT_OF_OBSTACLE_PREDICATE_HPP
#define SEMANTIC_REACH_TEST_RIGHT_OF_OBSTACLE_PREDICATE_HPP

class test_right_of_obstacle {};

#endif // SEMANTIC_REACH_TEST_RIGHT_OF_OBSTACLE_PREDICATE_HPP
