# Authors: Florian Lercher, Gerald Würsching, Tobias Mascetta. Cyber-Physical Systems Group, TUM


# --------------- Gitlab Internal Variables ------------------------
# Predefined internal variables from gitlab ci: see https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
# CI_REGISTRY: Gitlab Container Registry with Docker container for project
# CI_JOB_TOKEN: Token, valid as long as the job is running
# CI_PROJECT_DIR: path where project is cloned to and gitlab job runs from

# -------------- Variables from Docker container ----------------------------
# CRDC_DIR: Path to the installation of commonroad-drivability-checker in the Docker container
# CRREACH_DIR: Path to the installation of commonroad-reachable-set in the Docker container

stages:
  - static-check
  - compile
  - test

variables:
  CRDC_DIR: /dc
  CRREACH_DIR: /reach
  BUILD_JOBS: 4
  CONDA_ENV_PREFIX: commonroad-py

default:
  image: $CI_REGISTRY/cps/commonroad/commonroad-reach-semantic/deps:ci-cpp-env-model
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.lrz.de/".insteadOf "git@gitlab.lrz.de:"

.conda-init: &conda-init
  - conda init bash
  - source ~/.bashrc

.python-prepare: &python-prepare
  - python -m pip install --upgrade pip
  - pip install -r ./requirements.txt
  - conda install -c conda-forge spot

.python-versions: &python-versions
  - "3.10"

pycodestyle-commit:
  stage: static-check
  script:
    - pip install pycodestyle
    - git diff ${CI_COMMIT_BEFORE_SHA}...${CI_COMMIT_SHA} -- '*.py' | pycodestyle --max-line-length=120 --diff
  except:
    - merge_requests
  allow_failure: true

pycodestyle-merge-request:
  stage: static-check
  script:
    - pip install pycodestyle
    - git diff ${CI_MERGE_REQUEST_TARGET_BRANCH_SHA}...${CI_MERGE_REQUEST_SOURCE_BRANCH_SHA} -- '*.py' | pycodestyle --max-line-length=120 --diff
  only:
    - merge_requests
  allow_failure: true

clang-format:
  stage: static-check
  script: ./ci/clang-format.sh
  needs: [ ]

clang-tidy:
  stage: static-check
  variables:
    GIT_SUBMODULE_STRATEGY: recursive # initialize submodules before starting job
  script:
    - mkdir build && cd build
    - cmake -DCRDC_DIR="$CRDC_DIR" -DCRREACH_DIR="$CRREACH_DIR" -DPYTHON_VER="310" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - cmake --build . --target commonroad_protobuf # FIXME: this is required to generate the protobuf files (there is probably a better way to do this)
    - cd ..
    - ./ci/clang-tidy.sh
  needs: [ ]


### build C++ library ###
compile-cpp:
  stage: compile
  variables:
    GIT_SUBMODULE_STRATEGY: recursive # initialize submodules before starting job
  script:
    - *conda-init
    - conda activate "$CONDA_ENV_PREFIX$PYTHON_VER"
    - *python-prepare
    - mkdir build-debug && cd build-debug
    - cmake -DCRDC_DIR="$CRDC_DIR" -DCRREACH_DIR="$CRREACH_DIR" -DPYTHON_VER="$(echo $PYTHON_VER | sed -e 's/\.//g')" -DCMAKE_BUILD_TYPE=Debug -DADD_TESTS=true ..
    - cmake --build . -- -j $BUILD_JOBS
  parallel:
    matrix:
      - PYTHON_VER: *python-versions
  artifacts:
    paths:
      - pycrreachs.*.so
      - build-debug/lib
      - build-debug/cpp/tests/crreachs_test
    expire_in: 30 minutes
  needs: [ ]


### test Python ###
test-python:
  stage: test
  script:
    - *conda-init
    - conda activate "$CONDA_ENV_PREFIX$PYTHON_VER"
    - *python-prepare
    - cp pycrreachs.*.so commonroad_reach_semantic
    - cd tests
    - pytest .
  parallel:
    matrix:
      - PYTHON_VER: *python-versions
  needs:
    - job: compile-cpp
      artifacts: true

### test C++ ###
test-cpp:
  stage: test
  script:
    - *conda-init
    - conda activate "$CONDA_ENV_PREFIX$PYTHON_VER"
    - *python-prepare
    - cd build-debug
    - ./cpp/tests/crreachs_test
  parallel:
    matrix:
      - PYTHON_VER: *python-versions
  needs:
    - job: compile-cpp
      artifacts: true
